[package]
name = "rust_survival"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = "0.29.0"
crossterm = "0.28.1"
anyhow = "1.0"
rand = "0.8"
tui-term = "0.2.0"
include_dir = "0.7.4"
clap = {version = "4.5.53", features = ["derive"]}
